name: nirvar
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  http: ^1.2.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  dio: ^5.7.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.1.2
  get_it: ^7.7.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.3
  flutter_spinkit: ^5.2.1
  another_flushbar: ^1.12.30
  http_parser: ^4.0.0
  image_picker: ^1.1.2
  popover: ^0.3.1
  path: ^1.9.0
  pretty_qr_code: ^3.3.0
  share_plus: ^10.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#f4f4f2"
  image: "assets/images/native_splash.png"
  android_gravity: center
  ios_content_mode: scaleAspectFill
  fullscreen: true



flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf



