// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpFoimpQB835X71JcEKAtmKHSZv-arJE',
    appId: '1:534392329466:web:f957aa68835a224d91e543',
    messagingSenderId: '534392329466',
    projectId: 'nirvar-baffb',
    authDomain: 'nirvar-baffb.firebaseapp.com',
    storageBucket: 'nirvar-baffb.appspot.com',
    measurementId: 'G-QD04KK865K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3dfHXyd5eBoQFhXQyQiSfM_4kQ14axCs',
    appId: '1:534392329466:ios:2565bb3ea251cf2591e543',
    messagingSenderId: '534392329466',
    projectId: 'nirvar-baffb',
    storageBucket: 'nirvar-baffb.appspot.com',
    iosBundleId: 'com.nirvar.tech.patient.nirvar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxpFoimpQB835X71JcEKAtmKHSZv-arJE',
    appId: '1:534392329466:web:43e48c44b528213291e543',
    messagingSenderId: '534392329466',
    projectId: 'nirvar-baffb',
    authDomain: 'nirvar-baffb.firebaseapp.com',
    storageBucket: 'nirvar-baffb.appspot.com',
    measurementId: 'G-B9RJFXGJEM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dfHXyd5eBoQFhXQyQiSfM_4kQ14axCs',
    appId: '1:534392329466:ios:2565bb3ea251cf2591e543',
    messagingSenderId: '534392329466',
    projectId: 'nirvar-baffb',
    storageBucket: 'nirvar-baffb.appspot.com',
    iosBundleId: 'com.nirvar.tech.patient.nirvar',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkURVibZus5GwbDSjSk1OsAqe-3-zVCOA',
    appId: '1:534392329466:android:cee3ad021f7d7f2591e543',
    messagingSenderId: '534392329466',
    projectId: 'nirvar-baffb',
    storageBucket: 'nirvar-baffb.appspot.com',
  );

}